build: off

os: unstable

platform:
  - x64

skip_tags: true

environment:
  nodejs_version: "8"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm
  - npm install

before_test:
  - node --version
  - npm --version

test_script:
  - npm test

# after_test:
  # - npm run coverage
