const gulp = require('gulp');
const jetpack = require('fs-jetpack');
const bundle = require('./bundle');

// Spec files are scattered through the whole project. Here we're searching
// for them and generate one entry file which will run all the tests.
const generateEntryFile = (dir, destFileName, filePattern) => {
	const fileBanner = '// This file is generated automatically.\n' +
  '// All modifications will be lost.\n';

	return dir.findAsync('.', {matching: filePattern})
  .then(specPaths => {
	const fileContent = specPaths.map(path => {
		return `import './${path.replace(/\\/g, '/')}';`;
	}).join('\n');
	return dir.writeAsync(destFileName, fileBanner + fileContent);
})
  .then(() => {
	return dir.path(destFileName);
});
};

gulp.task('build-unit', ['environment'], () => {
	const testDir = jetpack.cwd('test');
	const destDir = jetpack.cwd('app');

	return generateEntryFile(testDir, 'specs.js.autogenerated', 'test.js')
  .then(entryFilePath => {
	return bundle(entryFilePath, destDir.path('specs.js'));
});
});
